---
shadowsocks:
  server_port: "8530"
  local_port: "1080"
  timeout: "600"
  encryption_method: "aes-256-cfb"
  tcp_fast_open: "true"
  enable_ota: "true"
  location: "/etc/shadowsocks-libev"
  password_file: "/etc/shadowsocks-libev/shadowsocks-password.txt"

nginx:
  domain_name: "planet.unixkoans.com"

postgresql:
  password_file: "/etc/postgresql/postgresql-password.txt"
