---
shadowsocks:
  server_port: "8530"
  local_port: "1080"
  timeout: "600"
  encryption_method: "aes-256-cfb"
  tcp_fast_open: "true"
  enable_ota: "false"
  location: "/etc/shadowsocks-libev"
  password_file: "/etc/shadowsocks-libev/shadowsocks-password.txt"

nginx:
  default_domain_name: "unixkoans.com"
  www_domain_name: "www.unixkoans.com"
  rss_domain_name: "planet.unixkoans.com"
  sync_domain_name: "sync.unixkoans.com"
  paste_domain_name: "paste.unixkoans.com"
  git_domain_name: "git.unixkoans.com"
  fonts_domain_name: "fonts.unixkoans.com"

postgresql:
  password_file: "/etc/postgresql/postgresql-password.txt"

stikked:
  user: "toyland"
  password_file: "/etc/stikked-password.txt"

user:
  name: "xuxiaodong"
  email: "xxdlhy@gmail.com"
