---
do:
  id: 39153100
  server_name: toyland
  ssh_key_name: toyland

droplet:
  size_id: 512mb
  region_id: sgp1
  image_id: debian-8-x64

linode:
  id: 2763580
  datacenter_id: 11
  plan_id: 1
  distro_id: 140
  server_name: toynode

vultr:
  dc_id: 25
  plan_id: 29
  distro_id: 193
  ssh_key_id: 58b917dc1b55b
  server_name: toydroid
