---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    default_release: jessie-backports
  with_items:
  - lsyncd

- name: Ensure /etc/lsyncd directory exist
  file:
    path: /etc/lsyncd
    state: directory

- name: Generate config
  template:
    src: lsyncd.conf.lua.j2
    dest: /etc/lsyncd/lsyncd.conf.lua
  notify: Restart lsyncd

- name: Enable service
  systemd:
    name: lsyncd
    state: started
    enabled: yes
