---
- name: Install requirements
  apt:
    name: "{{ item }}"
    default_release: jessie-backports
    state: present
  with_items:
  - build-essential
  - fakeroot
  - devscripts
  - debhelper
  - dh-make
  - lintian
  - debootstrap
  - pbuilder
  - git-buildpackage
  - git-dpm
  - dput
  - mini-dinstall

- name: Generate config
  template:
    src: pbuilderrc.j2
    dest: /var/lib/jenkins/.pbuilderrc

- name: Create base tarball
  command: pbuilder create
  args:
    creates: /var/cache/pbuilder/base.tgz

- name: Change owner
  file:
    path: /var/cache/pbuilder/result
    owner: jenkins
    group: jenkins

- name: Add cron
  cron:
    name: "Update pbuilder"
    minute: "30"
    hour: "1"
    user: root
    job: "pbuilder update"

- name: Add environment variable
  lineinfile:
    dest: /var/lib/jenkins/.bashrc
    regexp: '^export DEBEMAIL'
    line: 'export DEBEMAIL={{ user.email }}'
    create: yes

- name: Ensure directory exist
  file:
    path: /var/www/debian
    state: directory
    owner: jenkins
    group: jenkins

- name: Generate config
  template:
    src: "{{ item.src }}"
    dest: "/var/lib/jenkins/.{{ item.dest }}"
    owner: jenkins
    group: jenkins
  with_items:
  - { src: "dput.cf.j2", dest: "dput.cf" }
  - { src: "mini-dinstall.conf.j2", dest: "mini-dinstall.conf" }
  - { src: "gbp.conf.j2", dest: "gbp.conf" }

- name: Run mini-dinstall
  command: mini-dinstall -q -c /var/lib/jenkins/.mini-dinstall.conf
  args:
    creates: /var/www/debian/mini-dinstall/mini-dinstall.lock
  become: True
  become_method: su
  become_user: jenkins
