---
- name: Set DigitalOcean access token
  set_fact:
    do_api_token: "{{ do_api_token_entry }}"

- name: Get SSH key
  command: cat ~/.ssh/id_rsa.pub
  register: do_ssh_pub_key

- name: Ensure SSH key
  digital_ocean:
    state: present
    command: ssh
    name: "{{ droplet.ssh_key_name }}"
    ssh_pub_key: "{{ do_ssh_pub_key.stdout }}"
    api_token: "{{ do_api_token }}"
  register: do_ssh_key

- debug:
    msg: "SSH key ID: {{ do_ssh_key.ssh_key.id }}"

- name: Create new droplet
  digital_ocean:
    state: present
    command: droplet
    id: "{{ droplet.id }}"
    name: "{{ droplet.server_name }}"
    ssh_key_ids: "{{ do_ssh_key.ssh_key.id }}"
    size_id: "{{ droplet.size_id }}"
    region_id: "{{ droplet.region_id }}"
    image_id: "{{ droplet.image_id }}"
    wait_timeout: 500
    api_token: "{{ do_api_token }}"
  register: do_droplet

- debug:
    msg: "Droplet ID: {{ do_droplet.droplet.id }}"

- debug:
    msg: "Droplet IP: {{ do_droplet.droplet.ip_address }}"

- name: Wait until the server has  finished start
  wait_for:
    host: "{{ do_droplet.droplet.ip_address }}"
    port: 22
    search_regex: OpenSSH
    timeout: 600

- add_host:
    name: "{{ do_droplet.droplet.ip_address }}"
    groups: digital_ocean
